theme: jekyll-theme-cayman
var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l)
  return true;
}
GitHubPages::Dependencies.gems.each do |gem, version|
  s.add_dependency(gem, "= #{version}")
end
